---
- name: Get latest release version if helm_release_version is not set
  block:
  - name: Get github releases
    ansible.builtin.uri:
      url: "{{ helm_github_release_api_url }}"
    register: helm_github_releases

  - name: Get last release version
    ansible.builtin.set_fact:
      helm_release_version: "{{ helm_github_releases.json | map(attribute='tag_name') | first }}"
  when: helm_release_version is not defined

- name: Get stat on helm binary
  ansible.builtin.stat:
    path: "{{ helm_runtime_install_path }}/{{ helm_runtime_binary }}"
  register: helm_stat

- name: Install helm
  block:
  - name: Create tmp dir
    ansible.builtin.tempfile:
      state: directory
      suffix: helm
    register: helm_tmp_dir
  - name: Download and extract runtime app to tmp dir
    ansible.builtin.unarchive:
      src: "{{ helm_download_url }}"
      dest: "{{ helm_tmp_dir.path }}"
      include:
        - "linux-amd64/{{ helm_runtime_binary }}"
      creates: "{{ helm_tmp_dir.path }}/linux-amd64/{{ helm_runtime_binary }}"
      mode: 0755
      remote_src: yes

  - name: Move file from tmp dir to {{ helm_runtime_install_path }}
    ansible.builtin.copy:
      src: "{{ helm_tmp_dir.path }}/linux-amd64/{{ helm_runtime_binary }}"
      dest: "{{ helm_runtime_install_path }}/{{ helm_runtime_binary }}"
      mode: '0755'
      remote_src: yes
  
  - name: Remove tmp folder
    ansible.builtin.file:
      path: "{{ helm_tmp_dir.path }}"
      state: absent
  when: helm_stat.stat.exists is false

