---
- name: Get latest release version if release_version is not set
  block:
  - name: Get Kustomize releases
    ansible.builtin.uri:
      url: "{{ github_release_api_url }}"
    register: github_releases

  - name: Get last release version
    ansible.builtin.set_fact:
      release_version: "{{ (github_releases.json | selectattr('tag_name', 'match', 'kustomize' ) | map(attribute='tag_name') | first).split('/v') | last }}"
  when: release_version is not defined

- name: Download and extract runtime app
  ansible.builtin.unarchive:
    src: "{{ download_url }}"
    dest: "{{ runtime_install_path }}"
    include:
      - "{{ runtime_binary }}"
    creates: "{{ runtime_install_path }}/{{ runtime_binary }}"
    mode: 0755
    remote_src: yes
