- name: Install k3s if state is present
  ansible.builtin.import_tasks: present.yml
  when: state is not defined or state != 'absent'
- name: Install k3s if state is absent
  ansible.builtin.import_tasks: absent.yml
  when: state is defined and state == 'absent'