---

- name: Install prerequesits
  ansible.builtin.apt:
    name: conntrack
    state: present

- name: Add the ansible_user to docker group
  ansible.builtin.user:
    name: "{{ minikube_user }}"
    groups: docker
    append: yes

- name: Download and install latest minikube
  ansible.builtin.apt:
    deb: https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
    state: present

- name: Get minikube status
  ansible.builtin.shell: sudo -u {{ minikube_user }} minikube status
  register: minikube_status
  ignore_errors: True

- name: show minikube status
  ansible.builtin.debug:
    var: minikube_status

- name: start cluster
  ansible.builtin.shell: sudo -u {{ minikube_user }} minikube start --driver={{ minikube_driver }}
  when: minikube_status.rc != 0

- name: Add alias to minikube_users bashrc file
  ansible.builtin.lineinfile:
    path: /home/{{ minikube_user }}/.bashrc
    regexp: '^alias kubectl'
    line: alias kubectl="minikube kubectl --"
    owner: "{{ minikube_user }}"
    group: "{{ minikube_user }}"
    mode: '0644'
    